### ISSUE TITLE
request: ability to specify a minimum amount of RAM for the VM

### ISSUE THREAD

**Issue by hardyoyo** [rdsubhas/vagrant-faster#7]
My main host machine is a macbook air, at the moment. I am quite capable of manually specifying the memory used on my machine, but for the project I work on, it would be ideal if I could rely on a plugin such as this one to "usually get things right." Unfortunately, on a machine as small as mine (4GB RAM) taking 1/4 of RAM for a VM isn't quite enough RAM for my VM. 1/2 is a better choice. If I could specify a minimum in my Vagrantfile, and this plugin would implement a minimum, I'd have a nice solution for a project that could run on both modestly-speced hosts, as well as beefier hosts.

**Comment by hardyoyo** [comment]
This is almost a duplicate of #1, sorry.

**Comment by rdsubhas** [comment]
@hardyoyo Thanks, will close as dupe
